# Generated by Django 5.1.5 on 2025-03-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_document_event_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="department",
        ),
    ]
