# Generated by Django 5.1.5 on 2025-03-31 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_notification_user_delete_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-updated"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user_id",
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="base.project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
