# Generated by Django 5.1.5 on 2025-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_document_options_remove_document_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("doc", "DOC"), ("txt", "Text")], max_length=10
            ),
        ),
    ]
