# Generated by Django 5.1.5 on 2025-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
