# Generated by Django 5.1.5 on 2025-03-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "PDF"), ("doc", "DOC"), ("txt", "Text")],
                max_length=10,
                null=True,
            ),
        ),
    ]
