# Generated by Django 5.1.5 on 2025-04-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.project",
            ),
        ),
    ]
