# Generated by Django 5.1.5 on 2025-04-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_room_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
    ]
