# Generated by Django 5.1.5 on 2025-04-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_message_room"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["updated", "created"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="size",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
    ]
