# Generated by Django 5.1.5 on 2025-04-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_message_options_remove_document_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="project",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.RemoveField(
            model_name="document",
            name="type",
        ),
    ]
