# Generated by Django 5.1.5 on 2025-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_remove_document_project_remove_document_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
